### ISSUE TITLE
Find a way to display the labels

### ISSUE THREAD

**Issue by xMartin** [tosdr/tosdr-opera#1]
Opera doesn't seem to be able to let extensions display something in the browser chrome for each window independently. See http://my.opera.com/community/forums/topic.dml?id=1538962

If this is really impossible we could also cripple the extension so we don't have any labels showing up but only the popup on click just for the sake of having an extension.

**Comment by hugoroy** [comment]
Maybe a simple bookmarklet could be used for Opera then.

**Comment by xMartin** [comment]
So I got answer from an Opera guy: http://my.opera.com/community/forums/topic.dml?id=1538962&t=1349172629&page=1#comment13169922

Result: It's not possible. As commented on the Opera forum I think we should live with the confusing solution for the case of multiple windows open. If you have only one window open, it's perfectly fine.

**Comment by xMartin** [comment]
Made it work as explained above. 829ceabd2cd36f5541dab685e2505263612b9816

Please comment and reopen if any objection.
