### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xMartin** [tosdr/tosdr-opera#2]
So the extension is supposed to be under AGPL. But we want to host it at opera.com and they say you have to choose between a special Opera license to upload or - if you want open source - choose Apache 2.0.

http://dev.opera.com/articles/view/opera-extensions-publishing-guidelines/#chooselicense

@hugoroy said the first option might be ok with AGPL but it's not clear (right?).

Also is the way I applied the license to the code ok?

**Comment by hugoroy** [comment]
Well, basically Opera makes two points. AGPLv3 doesn't contradict the requirements set forth in #1. While #2 is specifically about "Open Source" they only say you "can" choose Apache 2.0. So it's not clear at all. So I hardly see why they would reject AGPLv3.

**Comment by xMartin** [comment]
Haha, Funny! So I uploaded the extension to Opera just to check how I enter the license but they just took the AGPLv3 from the metadata and that is it. Let's see how the moderation process goes.

**Comment by xMartin** [comment]
@hugoroy Can you check the current license status and close this if it's fine?

**Comment by hugoroy** [comment]
It looks good to me. Thanks for reminding me!
