### ISSUE TITLE
Support Opera 15

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/tosdr-opera#6]
see https://www.facebook.com/TermsOfServiceDidntRead/posts/648210938541531

> Hello the team :). Could you adapt Opera add-on to works with the recent Opera 
> next ? The current add-on works only for Opera 11 and 12, not for 15 (Opera Next). 
> Thank you very much, and good job ! :D

**Comment by xMartin** [comment]
The Chrome extension works in Opera 15 (currently in beta). But there is no download for that. I don't care too much for supporting the beta at the moment.

**Comment by xMartin** [comment]
Opera 15 is release since 2 July. This needs to be done now. Trying to find the time soon.

**Comment by xMartin** [comment]
Ok, I copied from the Chrome extension and did a few adjustments. Should be on the Opera page soon.

**Comment by xMartin** [comment]
Extension for Opera 15 is published: https://addons.opera.com/en/extensions/details/terms-of-service-didnt-read/

Old version is still available for Opera 12.
